set -g mode-keys vi
set -g mouse
bind -T copy-mode-vi v send -X begin-selection
# bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy" # macOS
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard" # Linux

